
image:
    file: .gitpod.dockerfile
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
tasks:
    - init: /usr/bin/python3 -m pip3 install pygame
      command: /usr/bin/python3 main.py
